### ISSUE TITLE
Meta Tags for Social Media (Must-have)

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/Arrival-Advisor-Website#11]
**Due: Mar. 19**

Please set up English Meta Tags for sharing the website on social media.

How to, if needed: https://css-tricks.com/essential-meta-tags-social-media/ though I imagine Wordpress might have a built in module to do this

We can use meta tag/meta description copy prepared by Lauren and I @CarlieNishi https://docs.google.com/spreadsheets/d/11P2aL6RtOrlccef7zR8QUWGTWjjOXJiTF0m85oK96RY/edit?usp=sharing

For the meta img, use: https://drive.google.com/open?id=1eIbMaYD4OAX3Mjyie5C3TA8sCyUVG7pu

Please also scrape the links for Facebook and Twitter to ensure the images and copy are generating properly. https://developers.facebook.com/tools/debug/
https://cards-dev.twitter.com/validator

**Comment by CarlieNishi** [comment]
Added both in.

**Comment by beni4** [comment]
Reopened as although we have done everything we can in terms of populating the seo plugins with the correct info and ensuring the og: codes are on the website, we are still unable to preview the posts/pages on social media platforms. 

Ive been scratching my head for a while at this one, but Im led to believe that facebook cannot scrape our site properly due to the SSL Certificate not being trusted by them. 

This is what facebook is telling us is the problem with the sharing functionality. 

Inferred Property
The ‘og:image’ property should be explicitly provided, even if a value can be inferred from other tags.
Missing Properties
The following required properties are missing: og:url, og:type, og:title, og:image, og:description, fb:app_id
SSL Error
Can’t validate SSL Certificate. Either it is self-signed (which will cause browser warnings) or it is invalid.
Curl Error
Curl error: 60 (SSL_CACERT)

As a result the first two errors that are showing up are a result of the SSL errors because on inspection of our page source all of the appropriate tags are actually in place.
Here are some suggestions on how to fix this. 

<img width="658" alt="Screenshot 2019-03-19 at 00 36 25" src="https://user-images.githubusercontent.com/24415918/54588267-b2ee3100-49df-11e9-8ee2-836403593055.png">
<img width="721" alt="Screenshot 2019-03-19 at 00 36 13" src="https://user-images.githubusercontent.com/24415918/54588268-b2ee3100-49df-11e9-896e-2b502e78f095.png">

https://www.whynopadlock.com
https://whatsmychaincert.com

@cherrielam 
@CarlieNishi

**Comment by cherrielam** [comment]
I would flag that when I set up the (Seedprod) temporary landing page plugin, I was able to generate the social media meta tags; I believe the SSL cert was installed then @beni4

**Comment by cherrielam** [comment]
In any case, do you need my support with getting the SSL cert uninstalled and reinstalled?

**Comment by beni4** [comment]
Im not sure what you mean by able to generate the social media meta tags? we are also able to generate the tags, they are currently on the website, however facebook is unable to scrape our site.  did you post successfully on social media with a preview etc to arrivaladvisor.ca when the landing page was live? 

Yes I would need your help as this issue can likely be resolved at the hosting account, this is where we can access the certificate.

**Comment by cherrielam** [comment]
I mean that Facebook was able to scrape the meta tags with the temporary landing page. @beni4 

And that's fine. @mackh @robinpuga can you help with the SSL cert issue above?

**Comment by cherrielam** [comment]
@beni4 @mackh let me know that
domain.com support is generating a chain file, and will send that by email when its made
then we can put it in place and that error will go away

**Comment by beni4** [comment]
Amazing, I really hope that this will clear this issue.

**Comment by cherrielam** [comment]
I believe this has now been resolved! Scrapes properly now :)
